// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Megj2W8TDkyv547Vt7lsKr5FQGGH9tk',
    appId: '1:555873172386:web:f3a947bd4ee61e84d410fb',
    messagingSenderId: '555873172386',
    projectId: 'fcmtest-4f962',
    authDomain: 'fcmtest-4f962.firebaseapp.com',
    storageBucket: 'fcmtest-4f962.appspot.com',
    measurementId: 'G-BG07W6SZ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaXImmYwf4_NC7-zMSRxoqu5_B-CGORe0',
    appId: '1:555873172386:android:b5144554dc81a28dd410fb',
    messagingSenderId: '555873172386',
    projectId: 'fcmtest-4f962',
    storageBucket: 'fcmtest-4f962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx08ZV5vXUVRbAKq7dmzDcu9F6KHBXtw4',
    appId: '1:555873172386:ios:84b0e74e6a0cc14bd410fb',
    messagingSenderId: '555873172386',
    projectId: 'fcmtest-4f962',
    storageBucket: 'fcmtest-4f962.appspot.com',
    iosClientId: '555873172386-0qdkjojbugcpl6ncst7a26pv7vh8urha.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesVictoriaCare',
  );
}
